---
title: "About Us"
title-block-banner: "img/home/yvr_dsm_stanley.png"
page-layout: full
---

<div class="centered-page-content">

# About SCGIS

The Society for Conservation GIS is an all-volunteer U.S. based non-profit organization focused on advancing conservation GIS globally by building and supporting conservation GIS practioners.

[Learn more about their mission here](https://www.scgis.org/about)

# Chapter Representatives

## Ramon Melser, PhD

Ramon is a postdoctoral research fellow in the [Integrated Remote Sensing Studio (IRSS)](https://irsslab.forestry.ubc.ca/), at the University of British Columbia (UBC). His research explores the use of multi-source remote sensing and geospatial datasets towards enhanced monitoring of the carbon cycle across boreal landscapes. During his time at UBC, Ramon has been involved in supporting a wide variety of undergraduate and graduate GIS courses, course development initiatives, and serves as a Teaching Assistant (TA) Training Coordinator for the Faculty of Forestry. As part of SCGIS Vancouver, he provides technical expertise on satellite remote sensing and looks forward to supporting local GIS practitioners in growing their skillset, highlighting their work, and connecting with their community.

## Sadie Russell, M.G.E.M

Sadie is a PhD student in UBC Forestry, where her graduate work has focused on applying remote sensing to disturbance ecology across British Columbia. Her current research investigates how drone-based lidar can support operational pyrosilviculture prescriptions to reduce wildfire risk. Sadie is deeply engaged in scientific education and communication, having developed climate change education materials for students from primary school through university. Through SCGIS, Sadie hopes to build community and uplift early-career scientists and conservationists.

## Liam Irwin, M.G.E.M.

Liam is a PhD Candidate at UBC Forestry working in remote sensing. His research focuses on integrating lidar (from drones and aircraft) into silvicultural practices. He is also involved in local conservation efforts at several regional parks including aiding in their integration of GIS into ecosystem restoration. As part of SCGIS Vancouver Liam hopes to bring technical and regional knowledge to help build the capacity of the GIS conservation community around Vancouver and beyond.

# Advisory Members

## Trevor Jones, PhD


</div>
